import json
import logging
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable

from fastapi import APIRouter, HTTPException, Query

logger = logging.getLogger(__name__)
router = APIRouter()

_generator = None
_get_db = None
_seed_cache: dict[str, Any] | None = None


def set_generator(generator):
    global _generator
    _generator = generator


def set_db_dependency(get_db_func):
    global _get_db
    _get_db = get_db_func


def _open_db():
    if not _get_db:
        raise HTTPException(status_code=503, detail="Database not configured")
    return next(_get_db())


def _seed() -> dict[str, Any]:
    global _seed_cache
    if _seed_cache is None:
        seed_path = Path(__file__).resolve().parents[3] / "data" / "demo_seed.json"
        with seed_path.open("r", encoding="utf-8") as handle:
            _seed_cache = json.load(handle)
    return _seed_cache


def _question_bank() -> list[dict[str, Any]]:
    return [node for node in _seed()["survey"]["nodes"] if node.get("type") != "adaptive"]


def _seed_survey() -> dict[str, Any]:
    return _seed()["survey"]


def _user_without_password(user: dict[str, Any]) -> dict[str, Any]:
    return {key: value for key, value in user.items() if key != "password"}


@router.post("/auth/login")
async def login(request: Dict[str, Any]):
    username = str(request.get("username", "")).strip()
    password = str(request.get("password", ""))
    for user in _seed()["users"]:
        if user["username"] == username and user["password"] == password:
            return {"user": _user_without_password(user), "token": f"local-{username}-{int(time.time())}"}
    raise HTTPException(status_code=401, detail="Invalid username or password")


@router.get("/surveys")
async def list_surveys():
    from models.survey import Survey

    db = _open_db()
    try:
        _ensure_seed_survey(db)
        rows = db.query(Survey).order_by(Survey.created_at.desc()).limit(100).all()
        surveys = []
        for row in rows:
            if row.survey_id == _seed_survey()["id"]:
                surveys.append(_seed_survey())
            else:
                surveys.append(row.survey_data)
        return {"surveys": surveys}
    finally:
        db.close()


@router.post("/surveys/generate")
async def generate_seed_survey(request: Dict[str, Any]):
    if not _generator:
        raise HTTPException(status_code=503, detail="Survey generator not initialized")

    prompt = str(request.get("prompt", "")).strip()
    user_id = request.get("user_id") or "sdrd"
    if len(prompt) < 10:
        raise HTTPException(status_code=400, detail="Prompt must be at least 10 characters")
    generated = _generator.generate(prompt, user_id)
    _save_generation(generated, prompt, user_id, 0)
    return {
        "survey": _generated_to_designer_survey(generated),
        "generated": generated,
        "note": "Draft generated by local LLM intent planner and trusted SATARK rules - review before publishing",
    }


@router.post("/generate")
async def generate_survey(request: Dict[str, Any]):
    if not _generator:
        raise HTTPException(status_code=503, detail="Survey generator not initialized")

    prompt = str(request.get("prompt", "")).strip()
    user_id = request.get("user_id") or "system"

    if len(prompt) < 10:
        raise HTTPException(status_code=400, detail="Prompt must be at least 10 characters")

    start = time.time()
    try:
        survey = _generator.generate(prompt, user_id)
        elapsed = round(time.time() - start, 3)
        _save_generation(survey, prompt, user_id, elapsed)
        return {"success": True, "survey": survey, "processing_time": elapsed}
    except Exception as exc:
        logger.error("Generation failed: %s", exc, exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/surveys/{survey_id}")
async def get_survey(survey_id: str):
    from models.survey import Survey

    if survey_id == _seed_survey()["id"]:
        return {"survey": _seed_survey()}

    db = _open_db()
    try:
        survey = db.query(Survey).filter(Survey.survey_id == survey_id).first()
        if not survey:
            raise HTTPException(status_code=404, detail="Survey not found")
        return {"survey": survey.survey_data}
    finally:
        db.close()


@router.get("/question-bank")
async def question_bank():
    return {"questions": _question_bank()}


@router.get("/codes")
async def codes():
    return {"codes": _seed()["codes"]}


@router.get("/llm/status")
async def llm_status():
    if not _generator or not getattr(_generator, "llm_planner", None):
        return {"enabled": False, "provider": "none"}
    planner = _generator.llm_planner
    return {
        "enabled": True,
        "provider": "ollama",
        "model": planner.model,
        "baseUrl": planner.base_url,
        "required": planner.required,
        "privacy": "local_inference_no_external_api",
    }


@router.post("/consent")
async def consent(request: Dict[str, Any]):
    return {"ok": True, "consentId": f"consent-{int(time.time() * 1000)}", "received": request}


@router.post("/prepopulate")
async def prepopulate(request: Dict[str, Any]):
    household_id = request.get("householdId") or request.get("household_id")
    household = next((item for item in _seed()["households"] if item["id"] == household_id), None)
    return {"household": household}


@router.post("/intelligence/sessions")
async def intelligence_session(request: Dict[str, Any]):
    return {"sessionId": f"session-{int(time.time() * 1000)}", "surveyId": request.get("surveyId")}


@router.post("/intelligence/answer")
async def intelligence_answer(request: Dict[str, Any]):
    return _evaluate_intelligence(
        answers=request.get("answers") or {},
        active_question_id=request.get("activeQuestionId"),
        persona=request.get("persona") or "genuine",
        speed_mode=request.get("speedMode") or "normal",
        elapsed_seconds=float(request.get("elapsedSeconds") or 0),
    )


@router.post("/responses")
async def submit_collection_response(request: Dict[str, Any]):
    from models.survey import SurveyResponse

    db = _open_db()
    try:
        _ensure_seed_survey(db)
        intelligence = request.get("intelligence") or {}
        answers = request.get("answers") or {}
        validation_flags = [
            layer for layer in intelligence.get("layers", []) if layer.get("status") in {"warn", "fail"}
        ]
        response = SurveyResponse(
            survey_id=request.get("surveyId") or _seed_survey()["id"],
            respondent_id=request.get("householdId"),
            responses=answers,
            channel="collection-client",
            duration_seconds=request.get("durationSeconds"),
            quality_score=int(intelligence.get("confidence") or 0),
            state=_seed()["households"][0]["prepop"]["state"],
            district=_seed()["households"][0]["prepop"]["district"],
            agent_id=request.get("enumeratorId"),
            is_validated=not any(flag.get("status") == "fail" for flag in validation_flags),
            validation_flags=validation_flags,
        )
        db.add(response)
        db.commit()
        return {"queued": False, "responseId": response.id, "qualityScore": response.quality_score}
    finally:
        db.close()


@router.post("/surveys/{survey_id}/responses")
async def submit_response(survey_id: str, request: Dict[str, Any]):
    from models.survey import Survey, SurveyResponse

    db = _open_db()
    try:
        survey = db.query(Survey).filter(Survey.survey_id == survey_id).first()
        if not survey and survey_id == _seed_survey()["id"]:
            _ensure_seed_survey(db)
            survey = db.query(Survey).filter(Survey.survey_id == survey_id).first()
        if not survey:
            raise HTTPException(status_code=404, detail="Survey not found")

        responses = request.get("responses")
        if not isinstance(responses, list) or not responses:
            raise HTTPException(status_code=400, detail="responses must be a non-empty list")

        validation_flags = _validate_response_payload(survey.survey_data, responses)
        quality_score = max(0, 100 - (len(validation_flags) * 10))

        response = SurveyResponse(
            survey_id=survey_id,
            respondent_id=request.get("respondent_id"),
            responses=responses,
            channel=request.get("channel", "web"),
            duration_seconds=request.get("duration_seconds"),
            quality_score=quality_score,
            state=request.get("state"),
            district=request.get("district"),
            agent_id=request.get("agent_id"),
            gps_latitude=request.get("gps_latitude"),
            gps_longitude=request.get("gps_longitude"),
            is_validated=not validation_flags,
            validation_flags=validation_flags,
        )
        db.add(response)
        db.commit()
        return {
            "success": not validation_flags,
            "response_id": response.id,
            "quality_score": quality_score,
            "validation_flags": validation_flags,
        }
    finally:
        db.close()


@router.get("/responses")
async def responses(status: str | None = Query(default=None)):
    from models.survey import SurveyResponse

    db = _open_db()
    try:
        rows = db.query(SurveyResponse).order_by(SurveyResponse.submitted_at.desc()).limit(100).all()
        response_items = [_response_to_flag(row) for row in rows if row.validation_flags]
        seed_flags = _seed_flags()
        combined = response_items + seed_flags
        if status == "flagged":
            return {"responses": combined}
        return {"responses": combined}
    finally:
        db.close()


@router.get("/responses/{response_id}")
async def response_detail(response_id: str):
    from models.survey import SurveyResponse

    db = _open_db()
    try:
        row = db.query(SurveyResponse).filter(SurveyResponse.id == response_id).first()
        if not row:
            raise HTTPException(status_code=404, detail="Response not found")
        return {
            "id": row.id,
            "surveyId": row.survey_id,
            "respondentId": row.respondent_id,
            "answers": row.responses,
            "qualityScore": row.quality_score,
            "validationFlags": row.validation_flags,
        }
    finally:
        db.close()


@router.post("/coding")
async def coding(request: Dict[str, Any]):
    raw_response = str(request.get("rawResponse") or request.get("raw_response") or "")
    return {"suggestion": _find_code_suggestion(raw_response)}


@router.post("/coding/review")
async def coding_review(request: Dict[str, Any]):
    return {"ok": True, "review": request}


@router.get("/enumerators")
async def enumerators():
    return {"enumerators": _seed()["enumerators"]}


@router.get("/enumerators/{enumerator_id}")
async def enumerator(enumerator_id: str):
    item = next((row for row in _seed()["enumerators"] if row["id"] == enumerator_id), None)
    if not item:
        raise HTTPException(status_code=404, detail="Enumerator not found")
    return {"enumerator": item}


@router.post("/actions")
async def actions(request: Dict[str, Any]):
    return {"ok": True, "action": request}


@router.get("/analytics")
async def analytics():
    return _analytics_snapshot()


@router.get("/analytics/summary")
async def analytics_summary():
    from models.survey import Survey, SurveyResponse

    db = _open_db()
    try:
        surveys = db.query(Survey).all()
        responses = db.query(SurveyResponse).all()
        validated = sum(1 for response in responses if response.is_validated)
        domain_counts = Counter(survey.domain for survey in surveys)
        avg_quality = (
            round(sum((response.quality_score or 0) for response in responses) / len(responses), 1)
            if responses else 0
        )
        return {
            "total_surveys": len(surveys),
            "total_responses": len(responses),
            "validation_rate": round(validated / len(responses) * 100, 1) if responses else 0,
            "average_quality_score": avg_quality,
            "domains": dict(domain_counts),
            "latest_survey": surveys[0].survey_id if surveys else None,
        }
    finally:
        db.close()


@router.get("/analytics/timeseries")
async def analytics_timeseries():
    from models.survey import SurveyResponse

    db = _open_db()
    try:
        buckets = defaultdict(int)
        for response in db.query(SurveyResponse).all():
            if response.submitted_at:
                buckets[response.submitted_at.date().isoformat()] += 1
        points = [{"date": date, "responses": count} for date, count in sorted(buckets.items())]
        return {"points": points}
    finally:
        db.close()


@router.get("/analytics/agents")
async def analytics_agents():
    from models.survey import SurveyResponse

    db = _open_db()
    try:
        stats = defaultdict(lambda: {"responses": 0, "validated": 0, "quality_total": 0})
        for response in db.query(SurveyResponse).all():
            agent = response.agent_id or "unassigned"
            stats[agent]["responses"] += 1
            stats[agent]["validated"] += 1 if response.is_validated else 0
            stats[agent]["quality_total"] += response.quality_score or 0

        agents = []
        for agent_id, values in stats.items():
            total = values["responses"]
            agents.append({
                "agent_id": agent_id,
                "responses": total,
                "validation_rate": round(values["validated"] / total * 100, 1) if total else 0,
                "average_quality_score": round(values["quality_total"] / total, 1) if total else 0,
            })
        return {"agents": sorted(agents, key=lambda item: item["responses"], reverse=True)}
    finally:
        db.close()


@router.post("/export")
async def export(request: Dict[str, Any]):
    file_format = request.get("format") or "csv"
    return {
        "fileName": f"satark-export.{file_format}",
        "content": "survey,responses,validated,error_rate\nPLFS 2025-26,1000,90,10",
    }


def _save_generation(survey: Dict[str, Any], prompt: str, user_id: str, elapsed: float):
    from models.survey import GenerationLog, Survey

    db = _open_db()
    try:
        db.add(Survey(
            survey_id=survey["survey_id"],
            title=survey["title"],
            description=survey.get("description"),
            domain=survey["domain"],
            survey_data=survey,
            created_by=user_id,
            total_questions=len(survey.get("questions", [])),
        ))
        db.add(GenerationLog(
            survey_id=survey["survey_id"],
            prompt=prompt,
            user_id=user_id,
            success=True,
            processing_time_seconds=elapsed,
        ))
        db.commit()
    finally:
        db.close()


def _generated_to_designer_survey(generated: dict[str, Any]) -> dict[str, Any]:
    nodes = []
    for question in generated.get("questions", []):
        validation = question.get("validation") or {}
        node: dict[str, Any] = {
            "id": question.get("id") or question.get("display_id"),
            "type": _designer_question_type(question.get("type")),
            "q": {
                "en": question.get("text") or "Question",
                "hi": question.get("text") or "Question",
                "ta": question.get("text") or "Question",
            },
        }
        if question.get("standard_code"):
            node["codeType"] = question["standard_code"]
        if question.get("options"):
            node["options"] = [
                option.get("label") or option.get("text") or str(option)
                for option in question["options"]
            ]
        if validation.get("min") is not None or validation.get("max") is not None:
            node["rules"] = {
                "range": [
                    validation.get("min", 0),
                    validation.get("max", 999999),
                ]
            }
        nodes.append(node)

    return {
        "id": generated.get("survey_id"),
        "title": {
            "en": generated.get("title") or "Generated Survey",
            "hi": generated.get("title") or "Generated Survey",
            "ta": generated.get("title") or "Generated Survey",
        },
        "nodes": nodes,
        "branches": {},
        "metadata": generated.get("metadata", {}),
    }


def _designer_question_type(value: Any) -> str:
    value = str(value or "text").lower()
    if value in {"single_choice", "select_one", "choice"}:
        return "choice"
    if value in {"multiple_choice", "select_many", "multi"}:
        return "multi"
    if value in {"integer", "decimal", "numeric", "number"}:
        return "number"
    if value in {"date"}:
        return "date"
    return "text"


def _save_seed_generation(prompt: str, user_id: str):
    from models.survey import GenerationLog

    db = _open_db()
    try:
        _ensure_seed_survey(db)
        db.add(GenerationLog(
            survey_id=_seed_survey()["id"],
            prompt=prompt,
            user_id=user_id,
            success=True,
            processing_time_seconds=0.05,
        ))
        db.commit()
    finally:
        db.close()


def _ensure_seed_survey(db):
    from models.survey import Survey

    existing = db.query(Survey).filter(Survey.survey_id == _seed_survey()["id"]).first()
    if existing:
        return existing
    survey = Survey(
        survey_id=_seed_survey()["id"],
        title=_seed_survey()["title"]["en"],
        description="Seed survey for SATARK role-based demo",
        domain="labour",
        status="published",
        survey_data=_seed_survey(),
        created_by="seed",
        tags=["employment", "household", "trusted-statistics"],
        total_questions=len(_question_bank()),
        prepopulation_rate=1,
    )
    db.add(survey)
    db.commit()
    return survey


def _validate_response_payload(survey: Dict[str, Any], responses: list[Dict[str, Any]]) -> list[Dict[str, str]]:
    by_question = {item.get("question_id"): item.get("value") for item in responses}
    flags = []
    for question in survey.get("questions", []):
        question_id = question.get("id")
        value = by_question.get(question_id)
        if question.get("required") and _is_blank(value):
            flags.append({"question_id": question_id, "message": "Required question missing"})
            continue
        validation = question.get("validation") or {}
        if not _is_blank(value) and question.get("type") == "number":
            try:
                numeric = float(value)
            except (TypeError, ValueError):
                flags.append({"question_id": question_id, "message": "Expected numeric value"})
                continue
            minimum = validation.get("min")
            maximum = validation.get("max")
            if minimum is not None and numeric < minimum:
                flags.append({"question_id": question_id, "message": f"Value below minimum {minimum}"})
            if maximum is not None and numeric > maximum:
                flags.append({"question_id": question_id, "message": f"Value above maximum {maximum}"})
    return flags


def _is_blank(value: Any) -> bool:
    return value is None or value == "" or value == []


def _find_code_suggestion(raw_value: str):
    value = raw_value.strip().lower()
    if not value:
        return None
    for record in _seed()["codes"]:
        matched = next((synonym for synonym in record.get("synonyms", []) if synonym.lower() in value), None)
        if matched or record["label"].lower() in value:
            source = "MoSPI NIC" if record.get("externalSource") else "Local"
            return {
                "code": record["code"],
                "type": record["type"],
                "label": record["label"],
                "confidence": 93 if record.get("externalSource") else 96,
                "source": source,
                "reason": f"Matched synonym '{matched or record['label']}' to {record['type']} {record['code']}",
            }
    return None


def _evaluate_intelligence(
    answers: dict[str, str],
    active_question_id: str | None,
    persona: str,
    speed_mode: str,
    elapsed_seconds: float,
):
    income = float(answers.get("income") or 0)
    occupation = answers.get("occupation")
    ref = _seed()["referenceDistributions"]
    too_fast = speed_mode == "too-fast" or elapsed_seconds <= 5
    unemployed_high_income = occupation == "Unemployed" and income > 50000
    outside_income = income > ref["income"]["p95"] or (income > 0 and income < ref["income"]["p05"])

    layers = [
        {"layer": "Completeness", "status": "pass", "reason": "Required responses are present"},
        {"layer": "Range", "status": "pass", "reason": "Numeric answers are inside permitted ranges"},
        {"layer": "Cross-field", "status": "pass", "reason": "Occupation and income do not conflict"},
        {"layer": "Context", "status": "pass", "reason": "Values are within regional reference distribution"},
        {"layer": "Behaviour", "status": "pass", "reason": "Response speed is consistent with expected survey pace"},
    ]
    confidence = 96 if persona == "genuine" else 84
    reason = "All validation layers are currently passing"

    if unemployed_high_income or too_fast or outside_income:
        layers = [
            {"layer": "Completeness", "status": "pass", "reason": "Required responses are present"},
            {"layer": "Range", "status": "pass", "reason": "Numeric answers are inside field-level ranges"},
            (
                {"layer": "Cross-field", "status": "fail", "reason": f"Income ₹{int(income):,} contradicts status 'Unemployed'"}
                if unemployed_high_income
                else {"layer": "Cross-field", "status": "pass", "reason": "Occupation and income do not conflict"}
            ),
            (
                {"layer": "Context", "status": "warn", "reason": f"₹{int(income):,} outside regional range ₹6,000-₹80,000"}
                if outside_income
                else {"layer": "Context", "status": "pass", "reason": "Income is inside regional reference range"}
            ),
            (
                {"layer": "Behaviour", "status": "fail", "reason": f"Answered in {max(3, round(elapsed_seconds))}s vs ~90s median"}
                if too_fast
                else {"layer": "Behaviour", "status": "pass", "reason": "Response speed is consistent with expected survey pace"}
            ),
        ]
        confidence = 46 if unemployed_high_income and too_fast else 68 if outside_income else 72
        reason = (
            "Cross-field validation found income inconsistent with 'Unemployed'"
            if unemployed_high_income
            else "Context validation found an outlier that needs review"
        )

    failed = sum(1 for layer in layers if layer["status"] == "fail")
    warned = sum(1 for layer in layers if layer["status"] == "warn")
    suggestion = _find_code_suggestion(answers.get("occupation", "")) if active_question_id == "occupation" else None

    return {
        "confidence": confidence,
        "trustLevel": _trust_level(confidence),
        "decision": "SIMPLIFY" if failed else "ASK",
        "nextQuestionId": None,
        "reason": reason,
        "layers": layers,
        "scores": {
            "engagement": 45 if too_fast else 92,
            "fatigue": 38 if too_fast else 84,
            "dropout": 44 if failed else 90,
            "quality": confidence,
        },
        "breakdown": {
            "validation": max(0, 100 - failed * 35 - warned * 12),
            "fraud": 42 if too_fast else 94,
            "evidence": 58 if failed else 90,
            "behaviour": 34 if too_fast else 91,
        },
        "suggestion": suggestion,
        "stored": False,
    }


def _trust_level(score: int | float) -> str:
    if score >= 75:
        return "Green"
    if score >= 55:
        return "Amber"
    return "Red"


def _seed_flags() -> list[dict[str, Any]]:
    return [
        {
            "id": "flag-seed-1",
            "enumeratorId": "ENUM-B",
            "enumeratorName": "Suspect Enumerator",
            "survey": _seed_survey()["title"]["en"],
            "reason": "Income ₹2,00,000 contradicts status 'Unemployed'",
            "trustScore": 40,
            "trustLevel": "Red",
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        }
    ]


def _response_to_flag(row) -> dict[str, Any]:
    enumerator = next((item for item in _seed()["enumerators"] if item["id"] == row.agent_id), None)
    first_flag = (row.validation_flags or [{}])[0]
    score = row.quality_score or 0
    return {
        "id": row.id,
        "enumeratorId": row.agent_id or "unassigned",
        "enumeratorName": enumerator["name"] if enumerator else row.agent_id or "Unassigned",
        "survey": _seed_survey()["title"]["en"],
        "reason": first_flag.get("reason") or first_flag.get("message") or "Validation warning",
        "trustScore": score,
        "trustLevel": _trust_level(score),
        "timestamp": row.submitted_at.isoformat() if row.submitted_at else time.strftime("%Y-%m-%dT%H:%M:%S"),
    }


def _analytics_snapshot() -> dict[str, Any]:
    enumerators = _seed()["enumerators"]
    return {
        "responsesToday": 186,
        "flagged": 14,
        "averageConfidence": 86.4,
        "activeEnumerators": len(enumerators),
        "totalResponses": 1000,
        "validatedRate": 90,
        "errorRate": 10,
        "ruralUrban": [33.4, 66.6],
        "genderRatio": {"male": 334, "female": 333},
        "confidenceScore": 86.4,
        "stateValidation": [
            {"state": "Uttar Pradesh", "rate": 89.5},
            {"state": "Maharashtra", "rate": 88.8},
            {"state": "Bihar", "rate": 75.8},
            {"state": "West Bengal", "rate": 79.2},
            {"state": "Madhya Pradesh", "rate": 76.9},
            {"state": "Tamil Nadu", "rate": 91.4},
        ],
        "enumeratorRanking": _enumerator_ranking(enumerators),
        "responseTrend": [
            {"label": "Mon", "responses": 120, "flagged": 8},
            {"label": "Tue", "responses": 148, "flagged": 11},
            {"label": "Wed", "responses": 171, "flagged": 16},
            {"label": "Thu", "responses": 154, "flagged": 13},
            {"label": "Fri", "responses": 186, "flagged": 15},
            {"label": "Sat", "responses": 132, "flagged": 9},
        ],
        "sectorDistribution": [
            {"sector": "Labour", "value": 38},
            {"sector": "Health", "value": 22},
            {"sector": "Agriculture", "value": 18},
            {"sector": "Education", "value": 12},
            {"sector": "Enterprise", "value": 10},
        ],
        "confidenceDistribution": [
            {"bucket": "0-50", "count": 32},
            {"bucket": "51-70", "count": 91},
            {"bucket": "71-85", "count": 240},
            {"bucket": "86-95", "count": 421},
            {"bucket": "96-100", "count": 216},
        ],
    }


def _enumerator_ranking(enumerators: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for index, enumerator in enumerate(enumerators):
        rows.append({
            **enumerator,
            "responses": enumerator["completed"] * 9 + index * 11,
            "errorRate": 14.1 if enumerator["trustLevel"] == "Red" else round(3.3 + index * 2.5, 1),
            "flaggedRate": 18.4 if enumerator["trustLevel"] == "Red" else round(4.1 + index, 1),
        })
    rows.extend([
        {**_seed()["enumerators"][0], "id": "ENUM004", "responses": 81, "errorRate": 3.3, "flaggedRate": 7},
        {**_seed()["enumerators"][0], "id": "ENUM008", "responses": 116, "errorRate": 3.3, "flaggedRate": 4.1},
        {**_seed()["enumerators"][0], "id": "ENUM006", "responses": 181, "errorRate": 5.8, "flaggedRate": 7},
        {**_seed()["enumerators"][0], "id": "ENUM001", "responses": 173, "errorRate": 5.9, "flaggedRate": 0.8},
        {**_seed()["enumerators"][1], "id": "ENUM009", "responses": 188, "errorRate": 14.1, "flaggedRate": 1.4},
    ])
    return rows
