import json
import logging
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException, Query

from app.auth.jwt import encode_token
from app.auth.password import verify_password
from app.auth.rbac import PERMISSIONS_BY_ROLE, get_current_user, require_scope
from app.config import settings

logger = logging.getLogger(__name__)
router = APIRouter()

_generator = None
_get_db = None


def set_generator(generator):
    global _generator
    _generator = generator


def set_db_dependency(get_db_func):
    global _get_db
    _get_db = get_db_func


def _open_db():
    if not _get_db:
        raise HTTPException(status_code=503, detail="Database not configured")
    return next(_get_db())


def _question_bank() -> list[dict[str, Any]]:
    path = Path(__file__).resolve().parents[3] / "data" / "question_bank" / "question_bank.json"
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    return data.get("questions", data if isinstance(data, list) else [])


@router.post("/auth/login")
async def login(request: Dict[str, Any]):
    from models.platform import PlatformUser

    username = str(request.get("username", "")).strip()
    password = str(request.get("password", ""))
    if not username or not password:
        raise HTTPException(status_code=401, detail="Invalid username or password")

    db = _open_db()
    try:
        row = db.query(PlatformUser).filter(PlatformUser.username == username).first()
        if row and row.is_active and verify_password(password, row.password_hash):
            scopes = sorted(PERMISSIONS_BY_ROLE.get(row.role, set()))
            token = encode_token(
                {
                    "sub": row.username,
                    "role": row.role,
                    "name": row.name,
                    "scopes": scopes,
                },
                secret=settings.SECRET_KEY,
            )
            return {
                "user": {"username": row.username, "role": row.role, "name": row.name},
                "token": token,
                "scopes": scopes,
            }
    finally:
        db.close()

    raise HTTPException(status_code=401, detail="Invalid username or password")


@router.get("/auth/me")
async def auth_me(user: dict = Depends(get_current_user)):
    return {
        "user": {"username": user["username"], "role": user["role"], "name": user.get("name", "")},
        "scopes": sorted(user["scopes"]),
        "source": user.get("source", "jwt"),
    }


@router.get("/surveys", dependencies=[Depends(require_scope("survey:read"))])
async def list_surveys(status: str | None = Query(default=None), owner: str | None = Query(default=None)):
    from models.survey import Survey

    db = _open_db()
    try:
        query = db.query(Survey).order_by(Survey.created_at.desc())
        if status:
            query = query.filter(Survey.status == status)
        if owner:
            query = query.filter(Survey.created_by == owner)
        rows = query.limit(200).all()
        surveys = []
        for row in rows:
            surveys.append(_survey_row_to_dict(row))
        return {"surveys": surveys}
    finally:
        db.close()


def _survey_row_to_dict(row) -> Dict[str, Any]:
    """Serialize a Survey row, preferring question_graph (SDRD JSONB) when present."""
    graph = row.question_graph
    if graph:
        base = dict(graph)
        base.setdefault("id", row.survey_id)
        base["status"] = row.status
        base["version"] = row.version
        return base
    data = dict(row.survey_data or {})
    data.setdefault("id", row.survey_id)
    data["status"] = row.status
    data["version"] = row.version
    return data


@router.post("/surveys/generate", dependencies=[Depends(require_scope("survey:write"))])
async def generate_seed_survey(request: Dict[str, Any], user: dict = Depends(get_current_user)):
    if not _generator:
        raise HTTPException(status_code=503, detail="Survey generator not initialized")

    prompt = str(request.get("prompt", "")).strip()
    user_id = request.get("user_id") or user.get("username") or "sdrd"
    if len(prompt) < 10:
        raise HTTPException(status_code=400, detail="Prompt must be at least 10 characters")
    start = time.time()
    generated = _generator.generate(prompt, user_id)
    elapsed = round(time.time() - start, 3)
    # Log-only â€” DO NOT create a Survey row. The draft lives in the FE builderStore
    # until the officer explicitly POSTs /api/surveys or PATCHes one (contract).
    _log_generation_only(generated, prompt, user_id, elapsed)
    return {
        "survey": _generated_to_designer_survey(generated),
        "generated": generated,
        "note": "Draft generated by local Gemma assist and trusted SATARK rules - review before publishing",
        "is_verdict": False,
        "needs_review": True,
        "sources": (generated.get("metadata") or {}).get("engine_trace", []),
        "confidence": (generated.get("metadata") or {}).get("llm", {}).get("confidence"),
    }


@router.post("/generate", dependencies=[Depends(require_scope("survey:write"))])
async def generate_survey(request: Dict[str, Any], user: dict = Depends(get_current_user)):
    if not _generator:
        raise HTTPException(status_code=503, detail="Survey generator not initialized")

    prompt = str(request.get("prompt", "")).strip()
    user_id = request.get("user_id") or user.get("username") or "system"

    if len(prompt) < 10:
        raise HTTPException(status_code=400, detail="Prompt must be at least 10 characters")

    start = time.time()
    try:
        survey = _generator.generate(prompt, user_id)
        elapsed = round(time.time() - start, 3)
        _save_generation(survey, prompt, user_id, elapsed)
        return {"success": True, "survey": survey, "processing_time": elapsed}
    except Exception as exc:
        logger.error("Generation failed: %s", exc, exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/surveys/{survey_id}", dependencies=[Depends(require_scope("survey:read"))])
async def get_survey(survey_id: str):
    from models.survey import Survey

    db = _open_db()
    try:
        survey = db.query(Survey).filter(Survey.survey_id == survey_id).first()
        if not survey:
            raise HTTPException(status_code=404, detail="Survey not found")
        return {"survey": _survey_row_to_dict(survey)}
    finally:
        db.close()


@router.post("/surveys", dependencies=[Depends(require_scope("survey:write"))])
async def create_survey_endpoint(request: Dict[str, Any], user: dict = Depends(get_current_user)):
    from app.services.survey_service import create_survey

    db = _open_db()
    try:
        row = create_survey(db, request, user.get("username") or "sdrd")
        return {"survey": _survey_row_to_dict(row)}
    finally:
        db.close()


@router.patch("/surveys/{survey_id}", dependencies=[Depends(require_scope("survey:write"))])
async def update_survey_endpoint(survey_id: str, request: Dict[str, Any]):
    from app.services.survey_service import update_survey

    db = _open_db()
    try:
        row = update_survey(db, survey_id, request)
        return {"survey": _survey_row_to_dict(row)}
    finally:
        db.close()


@router.post("/surveys/{survey_id}/publish", dependencies=[Depends(require_scope("survey:write"))])
async def publish_survey_endpoint(survey_id: str, user: dict = Depends(get_current_user)):
    from app.services.survey_service import publish_survey
    from services.events import publish as publish_event

    db = _open_db()
    try:
        result = publish_survey(db, survey_id, user.get("username") or "sdrd")
    finally:
        db.close()

    publish_event("survey.published", {
        "survey_id": survey_id,
        "version": result["version"],
        "published_by": user.get("username"),
    })
    return result


# ---------------------------------------------------------------------------
# Validation rules
# ---------------------------------------------------------------------------

@router.get("/validation-rules", dependencies=[Depends(require_scope("survey:read"))])
async def list_validation_rules_endpoint(survey_id: str | None = Query(default=None)):
    from app.services.validation_service import list_validation_rules

    db = _open_db()
    try:
        return {"rules": list_validation_rules(db, survey_id)}
    finally:
        db.close()


@router.post("/validation-rules", dependencies=[Depends(require_scope("survey:write"))])
async def create_validation_rule_endpoint(request: Dict[str, Any]):
    from app.services.validation_service import create_validation_rule

    db = _open_db()
    try:
        return {"rule": create_validation_rule(db, request)}
    finally:
        db.close()


@router.patch("/validation-rules/{rule_id}", dependencies=[Depends(require_scope("survey:write"))])
async def update_validation_rule_endpoint(rule_id: str, request: Dict[str, Any]):
    from app.services.validation_service import update_validation_rule

    db = _open_db()
    try:
        return {"rule": update_validation_rule(db, rule_id, request)}
    finally:
        db.close()


@router.delete("/validation-rules/{rule_id}", dependencies=[Depends(require_scope("survey:write"))])
async def delete_validation_rule_endpoint(rule_id: str):
    from app.services.validation_service import delete_validation_rule

    db = _open_db()
    try:
        return delete_validation_rule(db, rule_id)
    finally:
        db.close()


# ---------------------------------------------------------------------------
# Adaptive logic
# ---------------------------------------------------------------------------

@router.get("/adaptive-logic", dependencies=[Depends(require_scope("survey:read"))])
async def list_adaptive_logic_endpoint(survey_id: str | None = Query(default=None)):
    from app.services.validation_service import list_adaptive_logic

    db = _open_db()
    try:
        return {"rules": list_adaptive_logic(db, survey_id)}
    finally:
        db.close()


@router.post("/adaptive-logic", dependencies=[Depends(require_scope("survey:write"))])
async def create_adaptive_logic_endpoint(request: Dict[str, Any]):
    from app.services.validation_service import create_adaptive_logic

    db = _open_db()
    try:
        return {"rule": create_adaptive_logic(db, request)}
    finally:
        db.close()


@router.patch("/adaptive-logic/{rule_id}", dependencies=[Depends(require_scope("survey:write"))])
async def update_adaptive_logic_endpoint(rule_id: str, request: Dict[str, Any]):
    from app.services.validation_service import update_adaptive_logic

    db = _open_db()
    try:
        return {"rule": update_adaptive_logic(db, rule_id, request)}
    finally:
        db.close()


@router.delete("/adaptive-logic/{rule_id}", dependencies=[Depends(require_scope("survey:write"))])
async def delete_adaptive_logic_endpoint(rule_id: str):
    from app.services.validation_service import delete_adaptive_logic

    db = _open_db()
    try:
        return delete_adaptive_logic(db, rule_id)
    finally:
        db.close()


@router.get("/question-bank", dependencies=[Depends(require_scope("survey:read"))])
async def question_bank():
    return {"questions": _question_bank()}


@router.get("/codes", dependencies=[Depends(require_scope("survey:read"))])
async def codes(
    type: str | None = Query(default=None, alias="type"),
    q: str | None = Query(default=None),
):
    from models.platform import ClassificationCode

    db = _open_db()
    try:
        query = db.query(ClassificationCode)
        if type:
            query = query.filter(ClassificationCode.code_type == type.upper())
        rows = query.limit(500).all()
        results = [
            {
                "code": r.code,
                "type": r.code_type,
                "label": r.label,
                "synonyms": r.synonyms or [],
                "externalSource": r.external_source,
            }
            for r in rows
        ]
        if q:
            needle = q.lower()
            results = [
                c
                for c in results
                if needle in c.get("label", "").lower()
                or needle in c.get("code", "").lower()
                or any(needle in str(s).lower() for s in c.get("synonyms", []) or [])
            ]
        return {"codes": results}
    finally:
        db.close()


@router.get("/llm/status", dependencies=[Depends(require_scope("survey:read"))])
async def llm_status():
    if not _generator or not getattr(_generator, "llm_planner", None):
        return {"enabled": False, "provider": "none"}
    planner = _generator.llm_planner
    return {
        "enabled": True,
        "provider": "ollama",
        "model": planner.model,
        "baseUrl": planner.base_url,
        "required": planner.required,
        "privacy": "local_inference_no_external_api",
    }


@router.post("/consent", dependencies=[Depends(require_scope("collect:write"))])
async def consent(request: Dict[str, Any]):
    return {"ok": True, "consentId": f"consent-{int(time.time() * 1000)}", "received": request}


@router.post("/prepopulate", dependencies=[Depends(require_scope("collect:write"))])
async def prepopulate(request: Dict[str, Any]):
    from models.platform import Household

    household_id = request.get("householdId") or request.get("household_id")
    db = _open_db()
    try:
        household = db.get(Household, household_id) if household_id else None
        return {"household": None if not household else {"id": household.id, "prepop": household.prepopulated}}
    finally:
        db.close()


@router.post("/intelligence/sessions", dependencies=[Depends(require_scope("collect:write"))])
async def intelligence_session(request: Dict[str, Any]):
    return {"sessionId": f"session-{int(time.time() * 1000)}", "surveyId": request.get("surveyId")}


@router.post("/intelligence/answer", dependencies=[Depends(require_scope("collect:write"))])
async def intelligence_answer(request: Dict[str, Any]):
    return _evaluate_intelligence(
        answers=request.get("answers") or {},
        active_question_id=request.get("activeQuestionId"),
        persona=request.get("persona") or "genuine",
        speed_mode=request.get("speedMode") or "normal",
        elapsed_seconds=float(request.get("elapsedSeconds") or 0),
    )


@router.post("/responses", dependencies=[Depends(require_scope("collect:write"))])
async def submit_collection_response(request: Dict[str, Any]):
    from services.response_service import store_collection_response

    db = _open_db()
    try:
        return store_collection_response(db, request)
    finally:
        db.close()


@router.post("/surveys/{survey_id}/responses", dependencies=[Depends(require_scope("collect:write"))])
async def submit_response(survey_id: str, request: Dict[str, Any]):
    from models.survey import Survey, SurveyResponse

    db = _open_db()
    try:
        survey = db.query(Survey).filter(Survey.survey_id == survey_id).first()
        if not survey:
            raise HTTPException(status_code=404, detail="Survey not found")

        responses = request.get("responses")
        if not isinstance(responses, list) or not responses:
            raise HTTPException(status_code=400, detail="responses must be a non-empty list")

        validation_flags = _validate_response_payload(survey.survey_data, responses)
        quality_score = max(0, 100 - (len(validation_flags) * 10))

        response = SurveyResponse(
            survey_id=survey_id,
            respondent_id=request.get("respondent_id"),
            responses=responses,
            channel=request.get("channel", "web"),
            duration_seconds=request.get("duration_seconds"),
            quality_score=quality_score,
            state=request.get("state"),
            district=request.get("district"),
            agent_id=request.get("agent_id"),
            gps_latitude=request.get("gps_latitude"),
            gps_longitude=request.get("gps_longitude"),
            is_validated=not validation_flags,
            validation_flags=validation_flags,
        )
        db.add(response)
        db.commit()
        return {
            "success": not validation_flags,
            "response_id": response.id,
            "quality_score": quality_score,
            "validation_flags": validation_flags,
        }
    finally:
        db.close()


@router.get("/responses", dependencies=[Depends(require_scope("validation:review"))])
async def responses(status: str | None = Query(default=None)):
    from services.response_service import flagged_responses

    db = _open_db()
    try:
        return {"responses": flagged_responses(db, status=status)}
    finally:
        db.close()


@router.get("/responses/{response_id}", dependencies=[Depends(require_scope("validation:review"))])
async def response_detail(response_id: str):
    from services.response_service import response_detail as load_response_detail

    db = _open_db()
    try:
        detail = load_response_detail(db, response_id)
        if not detail:
            raise HTTPException(status_code=404, detail="Response not found")
        return detail
    finally:
        db.close()


@router.post("/coding", dependencies=[Depends(require_scope("survey:read"))])
async def coding(request: Dict[str, Any]):
    from models.platform import ClassificationCode

    raw_response = str(request.get("rawResponse") or request.get("raw_response") or "")
    needle = raw_response.strip().lower()
    suggestion = None
    if needle:
        db = _open_db()
        try:
            rows = db.query(ClassificationCode).limit(500).all()
            for row in rows:
                haystack = " ".join([row.label or "", row.code or ""] + list(row.synonyms or [])).lower()
                if needle in haystack:
                    suggestion = {
                        "code": row.code,
                        "type": row.code_type,
                        "label": row.label,
                        "confidence": 93,
                        "source": row.external_source or "classification_codes",
                        "reason": f"Matched persisted {row.code_type} code {row.code}",
                    }
                    break
        finally:
            db.close()
    return {
        "suggestion": suggestion,
        "is_verdict": False,
        "needs_review": True,
    }


@router.post("/coding/review", dependencies=[Depends(require_scope("coding:review"))])
async def coding_review(request: Dict[str, Any]):
    return {"ok": True, "review": request}


@router.get("/enumerators", dependencies=[Depends(require_scope("dashboard:view"))])
async def enumerators():
    from services.dashboard_data import enumerators_payload

    db = _open_db()
    try:
        return {"enumerators": enumerators_payload(db)}
    finally:
        db.close()


@router.get("/enumerators/{enumerator_id}", dependencies=[Depends(require_scope("dashboard:view"))])
async def enumerator(enumerator_id: str):
    from services.dashboard_data import enumerator_payload

    db = _open_db()
    try:
        item = enumerator_payload(db, enumerator_id)
    finally:
        db.close()
    if not item:
        raise HTTPException(status_code=404, detail="Enumerator not found")
    return {"enumerator": item}


@router.post("/actions", dependencies=[Depends(require_scope("dashboard:view"))])
async def actions(request: Dict[str, Any]):
    return {"ok": True, "action": request}


@router.get("/analytics", dependencies=[Depends(require_scope("dashboard:view"))])
async def analytics():
    from services.dashboard_data import analytics_snapshot

    db = _open_db()
    try:
        return analytics_snapshot(db)
    finally:
        db.close()


@router.get("/analytics/summary", dependencies=[Depends(require_scope("dashboard:view"))])
async def analytics_summary():
    from models.survey import Survey, SurveyResponse

    db = _open_db()
    try:
        surveys = db.query(Survey).all()
        responses = db.query(SurveyResponse).all()
        validated = sum(1 for response in responses if response.is_validated)
        domain_counts = Counter(survey.domain for survey in surveys)
        avg_quality = (
            round(sum((response.quality_score or 0) for response in responses) / len(responses), 1)
            if responses else 0
        )
        return {
            "total_surveys": len(surveys),
            "total_responses": len(responses),
            "validation_rate": round(validated / len(responses) * 100, 1) if responses else 0,
            "average_quality_score": avg_quality,
            "domains": dict(domain_counts),
            "latest_survey": surveys[0].survey_id if surveys else None,
        }
    finally:
        db.close()


@router.get("/analytics/timeseries", dependencies=[Depends(require_scope("dashboard:view"))])
async def analytics_timeseries():
    from models.survey import SurveyResponse

    db = _open_db()
    try:
        buckets = defaultdict(int)
        for response in db.query(SurveyResponse).all():
            if response.submitted_at:
                buckets[response.submitted_at.date().isoformat()] += 1
        points = [{"date": date, "responses": count} for date, count in sorted(buckets.items())]
        return {"points": points}
    finally:
        db.close()


@router.get("/analytics/agents", dependencies=[Depends(require_scope("dashboard:view"))])
async def analytics_agents():
    from models.survey import SurveyResponse

    db = _open_db()
    try:
        stats = defaultdict(lambda: {"responses": 0, "validated": 0, "quality_total": 0})
        for response in db.query(SurveyResponse).all():
            agent = response.agent_id or "unassigned"
            stats[agent]["responses"] += 1
            stats[agent]["validated"] += 1 if response.is_validated else 0
            stats[agent]["quality_total"] += response.quality_score or 0

        agents = []
        for agent_id, values in stats.items():
            total = values["responses"]
            agents.append({
                "agent_id": agent_id,
                "responses": total,
                "validation_rate": round(values["validated"] / total * 100, 1) if total else 0,
                "average_quality_score": round(values["quality_total"] / total, 1) if total else 0,
            })
        return {"agents": sorted(agents, key=lambda item: item["responses"], reverse=True)}
    finally:
        db.close()


@router.post("/export", dependencies=[Depends(require_scope("dashboard:view"))])
async def export(request: Dict[str, Any]):
    file_format = request.get("format") or "csv"
    return {
        "fileName": f"satark-export.{file_format}",
        "content": "survey,responses,validated,error_rate\nPLFS 2025-26,1000,90,10",
    }


def _save_generation(survey: Dict[str, Any], prompt: str, user_id: str, elapsed: float):
    """Legacy helper kept for backwards-compat with v1 /generate endpoint.

    The SDRD-facing /api/surveys/generate uses _log_generation_only() instead,
    which writes ONLY to generation_logs (no Survey row) per the prompt contract:
    'NO writes until officer edits/publishes; draft is held in builderStore'.
    """
    from models.survey import GenerationLog, Survey

    db = _open_db()
    try:
        db.add(Survey(
            survey_id=survey["survey_id"],
            title=survey["title"],
            description=survey.get("description"),
            domain=survey["domain"],
            survey_data=survey,
            created_by=user_id,
            total_questions=len(survey.get("questions", [])),
        ))
        db.add(GenerationLog(
            survey_id=survey["survey_id"],
            prompt=prompt,
            user_id=user_id,
            success=True,
            processing_time_seconds=elapsed,
        ))
        db.commit()
    finally:
        db.close()


def _log_generation_only(survey: Dict[str, Any], prompt: str, user_id: str, elapsed: float):
    """Persist only the GenerationLog row â€” no Survey row.

    Honors the SDRD contract: prompt-to-canvas produces a draft held client-side
    until the officer explicitly Creates/Publishes.
    """
    from models.survey import GenerationLog

    db = _open_db()
    try:
        db.add(GenerationLog(
            survey_id=survey.get("survey_id") or "draft",
            prompt=prompt,
            user_id=user_id,
            success=True,
            processing_time_seconds=elapsed,
        ))
        db.commit()
    finally:
        db.close()


def _generated_to_designer_survey(generated: dict[str, Any]) -> dict[str, Any]:
    nodes = []
    for question in generated.get("questions", []):
        validation = question.get("validation") or {}
        node: dict[str, Any] = {
            "id": question.get("id") or question.get("display_id"),
            "type": _designer_question_type(question.get("type")),
            "q": {
                "en": question.get("text") or "Question",
                "hi": question.get("text") or "Question",
                "ta": question.get("text") or "Question",
            },
        }
        if question.get("standard_code"):
            node["codeType"] = question["standard_code"]
        if question.get("options"):
            node["options"] = [
                option.get("label") or option.get("text") or str(option)
                for option in question["options"]
            ]
        if validation.get("min") is not None or validation.get("max") is not None:
            node["rules"] = {
                "range": [
                    validation.get("min", 0),
                    validation.get("max", 999999),
                ]
            }
        nodes.append(node)

    return {
        "id": generated.get("survey_id"),
        "title": {
            "en": generated.get("title") or "Generated Survey",
            "hi": generated.get("title") or "Generated Survey",
            "ta": generated.get("title") or "Generated Survey",
        },
        "nodes": nodes,
        "branches": {},
        "metadata": generated.get("metadata", {}),
    }


def _designer_question_type(value: Any) -> str:
    value = str(value or "text").lower()
    if value in {"single_choice", "select_one", "choice"}:
        return "choice"
    if value in {"multiple_choice", "select_many", "multi"}:
        return "multi"
    if value in {"integer", "decimal", "numeric", "number"}:
        return "number"
    if value in {"date"}:
        return "date"
    return "text"


def _validate_response_payload(survey: Dict[str, Any], responses: list[Dict[str, Any]]) -> list[Dict[str, str]]:
    by_question = {item.get("question_id"): item.get("value") for item in responses}
    flags = []
    for question in survey.get("questions", []):
        question_id = question.get("id")
        value = by_question.get(question_id)
        if question.get("required") and _is_blank(value):
            flags.append({"question_id": question_id, "message": "Required question missing"})
            continue
        validation = question.get("validation") or {}
        if not _is_blank(value) and question.get("type") == "number":
            try:
                numeric = float(value)
            except (TypeError, ValueError):
                flags.append({"question_id": question_id, "message": "Expected numeric value"})
                continue
            minimum = validation.get("min")
            maximum = validation.get("max")
            if minimum is not None and numeric < minimum:
                flags.append({"question_id": question_id, "message": f"Value below minimum {minimum}"})
            if maximum is not None and numeric > maximum:
                flags.append({"question_id": question_id, "message": f"Value above maximum {maximum}"})
    return flags


def _is_blank(value: Any) -> bool:
    return value is None or value == "" or value == []


def _evaluate_intelligence(
    answers: dict[str, str],
    active_question_id: str | None,
    persona: str,
    speed_mode: str,
    elapsed_seconds: float,
):
    from services.intelligence_adapter import evaluate_intelligence_contract

    return evaluate_intelligence_contract(
        answers=answers,
        active_question_id=active_question_id,
        persona=persona,
        speed_mode=speed_mode,
        elapsed_seconds=elapsed_seconds,
    )

